my_platform/app/routes.py
# app/routes.py
print("Routes file loaded!")  # Add this line

from flask import render_template, redirect, url_for, flash, abort, request, jsonify, session
from flask_login import login_user, logout_user, login_required, current_user, LoginManager
from app import db, create_app, celery
from app.forms import RegistrationForm, LoginForm
from app.forms import AddContentForm, CreateLearningPathForm, LearningPreferencesForm
from app.models import User, LearningPath, Content, StudyPlanProgress
from app.forms import AddContentToPathForm, EditProfileForm
from app.personalization import generate_personalized_learning_plan_task, convert_html_to_dict, convert_dict_to_html
from datetime import datetime
from werkzeug.exceptions import HTTPException  # import HTTPException instead of abort
from flask import Blueprint
from flask import current_app
import json

login_manager = LoginManager()
login_manager.login_view = 'main.login'
main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')

@main.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(username=form.username.data).first()
        if existing_user:
            flash('Username already taken. Please choose a different one.')
            return redirect(url_for('main.register'))

        existing_email = User.query.filter_by(email=form.email.data).first()
        if existing_email:
            flash('Email already registered. Please use a different one or log in.')
            return redirect(url_for('main.register'))

        if form.password.data != form.password_confirm.data:
            flash('Password and confirmation do not match. Please try again.')
            return redirect(url_for('main.register'))

        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Registration successful.')
        return redirect(url_for('main.login'))

    return render_template('register.html', form=form)

@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid email or password.')
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        session['user_id'] = user.id  # Store the user's id in the session
        return redirect(url_for('main.dashboard'))
    return render_template('login.html', form=form)


@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@main.route('/create_learning_path', methods=['GET', 'POST'])
@login_required
def create_learning_path():
    form = CreateLearningPathForm()
    if form.validate_on_submit():
        title = form.title.data
        topic_of_study = form.topic_of_study.data
        current_skill_level = form.current_skill_level.data
        target_skill_level = form.target_skill_level.data
        time_frame = form.time_frame.data
        flash('Your learning path is currently being generated and should be available in the next few minutes.', 'success')

        # Generate personalized learning plan
        generate_personalized_learning_plan_task.apply_async(args=[current_user.id, current_user.username, title, topic_of_study, current_skill_level, target_skill_level, time_frame, current_app.config['OPENAI_API_KEY']])

        return redirect(url_for('main.dashboard'))
        
    return render_template('create_learning_path.html', title='Create Learning Path', form=form)


# @main.route('/update_task_completion', methods=['POST'])
# def update_task_completion():
#     data = request.get_json()
#     learning_path_id = data.get('learning_path_id')
#     task_index = data.get('task_index')

#     # Update the learning path's completed tasks in the database
#     learning_path = LearningPath.query.get(learning_path_id)
#     if learning_path:
#         week_number = get_week_number_from_task_index(task_index)
#         learning_path.mark_task_completed(week_number, task_index)
#         db.session.commit()
#         return jsonify({'message': 'Task completion updated'})
#     else:
#         return jsonify({'message': 'Learning path not found'}), 404

@main.route('/learning_paths')
@login_required
def learning_paths():
    paths = LearningPath.query.filter_by(user_id=current_user.id).all()
    return render_template('learning_paths.html', paths=paths)


# @main.route('/learning_path/<int:path_id>', methods=['GET', 'POST'])
# @login_required
# def view_learning_path(path_id):
#     path = LearningPath.query.get_or_404(path_id)
#     if path.user_id != current_user.id:
#         abort(403)
#     form = AddContentToPathForm()
#     form.content.choices = [(c.id, c.title) for c in Content.query.filter_by(user_id=current_user.id).all()]
#     if form.validate_on_submit():
#         content = Content.query.get(form.content.data)
#         content.learning_path_id = path_id
#         db.session.commit()
#         flash('Content added to learning path.')
#         return redirect(url_for('main.view_learning_path', path_id=path_id))
#     return render_template('view_learning_path.html', path=path, form=form)

@main.route('/learning_path/<int:path_id>', methods=['GET', 'POST'])
@login_required
def view_learning_path(path_id):
    path = LearningPath.query.get_or_404(path_id)
    if path.user_id != current_user.id:
        abort(403)
    form = AddContentToPathForm()
    form.content.choices = [(c.id, c.title) for c in Content.query.filter_by(user_id=current_user.id).all()]
    if form.validate_on_submit():
        content = Content.query.get(form.content.data)
        content.learning_path_id = path_id
        db.session.commit()
        flash('Content added to learning_path.')
        return redirect(url_for('main.view_learning_path', path_id=path_id))

    progress_data = get_progress_from_database(current_user.id, path_id)  # Fetch the progress data
    return render_template('view_learning_path.html', path=path, form=form, progress_data=progress_data)


@main.route('/update_progress', methods=['POST'])
def update_progress():
    data = request.get_json()
    print(f"Received data: {data}")
    user_id = data.get('user_id')
    progress_data = data.get('progress_data')

    # Retrieve the learning path
    path_id = data.get('path_id')
    path = LearningPath.query.get(path_id)

    if path:
        # Update the progress for each task
        for week_number, week_data in progress_data.items():
            for task_id, task_data in week_data.items():
                checked = task_data.get('checked', False)

                # Check if the progress exists in the database
                progress = StudyPlanProgress.query.filter_by(
                    user_id=user_id,
                    learning_path_id=path_id,
                    week_number=week_number,
                    task_id=task_id
                ).first()

                if progress:
                    # Update the progress
                    progress.checked = checked
                else:
                    # Create a new progress entry
                    progress = StudyPlanProgress(
                        user_id=user_id,
                        learning_path_id=path_id,
                        week_number=week_number,
                        task_id=task_id,
                        checked=checked
                    )
                    db.session.add(progress)

        # Update the contents attribute with the new checkbox state
        path.update_contents(progress_data)

        # Commit the database changes
        db.session.commit()

        # Calculate overall progress
        total_tasks = path.contents.count('data-task=')
        completed_tasks = StudyPlanProgress.query.filter_by(
            user_id=user_id,
            learning_path_id=path_id,
            checked=True
        ).count()
        overall_progress = int((completed_tasks / total_tasks) * 100) if total_tasks > 0 else 0

        return jsonify({'progress': overall_progress}), 200
    else:
        return jsonify({'error': 'Learning path not found'}), 404

@main.route('/get_progress')
def get_progress():
    user_id = request.args.get('user_id')
    path_id = request.args.get('path_id')

    if not user_id or not path_id:
        abort(400, "Invalid parameters")

    try:
        progress_data = get_progress_from_database(user_id, path_id)
    except Exception as e:
        abort(500, "Failed to get progress from database: " + str(e))

    # Ensure keys are strings
    try:
        progress_data_str_keys = {str(k): v for k, v in progress_data.items()}
        print("Test")
        print(progress_data_str_keys)
        print("End of test")
    except Exception as e:
        abort(500, "Failed to convert progress data keys to strings: " + str(e))

    return jsonify(progress_data_str_keys), 200


def get_progress_from_database(user_id, path_id):
    progress_data = {}
    
    # Query StudyPlanProgress to get progress of a user on a specific learning path
    progress_entries = StudyPlanProgress.query.filter_by(user_id=user_id, learning_path_id=path_id).all()
    print(progress_entries)

    # Populate progress_data dictionary from the query results
    for entry in progress_entries:
        if entry.week_number not in progress_data:
            progress_data[entry.week_number] = {}
        progress_data[entry.week_number][entry.task_id] = {'checked': entry.checked}

    return progress_data

my_platform/app/templates/add_content.html
<!-- app/templates/add_content.html -->
{% extends 'base.html' %}

{% block content %}
<h2>Add Content</h2>
<form action="" method="post">
    {{ form.hidden_tag() }}
    {{ form.title.label }} {{ form.title(size=32) }}<br>
    {{ form.source.label }} {{ form.source(size=32) }}<br>
    {{ form.content_type.label }} {{ form.content_type }}<br>
    {{ form.difficulty.label }} {{ form.difficulty }}<br>
    {{ form.submit() }}
</form>
{% endblock %}

my_platform/app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>InfiniLearn AI</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f1f5f9;
            color: #4a4a4a;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .container {
            width: 100%;
        }
        nav {
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px 0;
            background-color: #3498db;
            color: #fff;
        }
        .nav {
            display: flex;
            justify-content: space-evenly;
            width: 100%;
        }
        nav a {
            color: #fff;
            text-decoration: none;
            padding: 10px;
            border-radius: 5px;
            transition: background-color 0.3s;
        }
        nav a:hover {
            background-color: #1a5276;
        }
        .flash-messages {
            width: 100%;
            display: flex;
            justify-content: center;
            color: #e74c3c;
        }
        .flash-message-container {
            text-align: center;
        }
        .content {
            margin-bottom: 40px;
        }
    </style>
</head>
<body>
    <!-- Navigation -->
    <nav class="container">
        <div class="nav">
            <a href="{{ url_for('main.dashboard') }}">My Dashboard</a>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('main.create_learning_path') }}">Add Learning Plan</a> 
                <a href="{{ url_for('main.learning_paths') }}">All Learning Plans</a> 
                <a href="{{ url_for('main.profile') }}">My Profile</a> 
                <a href="{{ url_for('main.logout') }}">Logout</a> 
            {% else %}
                <a href="{{ url_for('main.register') }}">Register</a> 
                <a href="{{ url_for('main.login') }}">Log In</a> 
            {% endif %}
        </div>
    </nav>
    
   <!-- Flash messages -->
    <div class="container flash-messages">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="flash-message-container">
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    </div>
    
    <!-- Content block -->
    <div class="container content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

my_platform/app/templates/create_learning_path.html
{% extends "base.html" %}

{% block content %}
    <style>
        .form-container {
            max-width: 400px;
            margin: auto;
            padding: 30px;
            background-color: #f1f5f9;
            border-radius: 10px;
            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.2);
        }
        .form-container h1 {
            text-align: center;
            color: #3498db;
            margin-bottom: 20px;
            font-size: 2em;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        .form-control {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            transition: border-color 0.3s;
        }
        .form-control:focus {
            outline: none;
            border-color: #3498db;
        }
        .text-danger {
            color: red;
        }
        .btn-primary {
            display: block;
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #3498db;
            color: #fff;
            font-weight: bold;
            transition: background-color 0.3s;
        }
        .btn-primary:hover {
            background-color: #1a5276;
        }
    </style>
    <div class="form-container">
        <h1>Create Learning Path</h1>
        <form method="POST" action="/create_learning_path">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <label for="{{ form.title.id }}" class="form-label">{{ form.title.label }}</label>
                {{ form.title(class="form-control") }}
                {% for error in form.title.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="{{ form.topic_of_study.id }}" class="form-label">{{ form.topic_of_study.label }}</label>
                {{ form.topic_of_study(class="form-control") }}
                {% for error in form.topic_of_study.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="{{ form.current_skill_level.id }}" class="form-label">{{ form.current_skill_level.label }}</label>
                {{ form.current_skill_level(class="form-control") }}
                {% for error in form.current_skill_level.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="{{ form.target_skill_level.id }}" class="form-label">{{ form.target_skill_level.label }}</label>
                {{ form.target_skill_level(class="form-control") }}
                {% for error in form.target_skill_level.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="{{ form.time_frame.id }}" class="form-label">{{ form.time_frame.label }}</label>
                {{ form.time_frame(class="form-control") }}
                {% for error in form.time_frame.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">{{ form.submit.label }}</button>
            </div>
        </form>
    </div>
{% endblock %}
           

my_platform/app/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .dashboard-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 50px;
            background-color: #f1f5f9;
            border-radius: 10px;
            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.2);
        }
        .dashboard-container h1 {
            color: #3498db;
            margin-bottom: 20px;
            font-size: 2.5em;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
            padding: 0 20px; /* Added padding to the left and right */
        }
        .dashboard-container p {
            margin-bottom: 20px;
            line-height: 1.6;
            font-size: 1.2em;
            text-align: center;
        }
        .dashboard-container ul {
            list-style-type: none;
            padding: 0;
            margin-bottom: 20px;
        }
        .dashboard-container li {
            margin-bottom: 10px;
        }
        .dashboard-container li a {
            color: #3498db;
            text-decoration: none;
            transition: color 0.3s;
        }
        .dashboard-container li a:hover {
            color: #1a5276;
        }
    </style>
    <div class="dashboard-container">
        <h1>Welcome to the Dashboard</h1>
        <p>Your personalized learning dashboard is here to help you excel in your learning journey.</p>
        <p>Explore your learning plans to enhance your skills and achieve your goals.</p>
    </div>
{% endblock %}

my_platform/app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .welcome-container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: calc(100vh - 100px);
            text-align: center;
            background-color: #f1f5f9;
            border-radius: 10px;
            padding: 30px;
            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.2);
        }
        .welcome-container h1 {
            color: #3498db;
            margin-bottom: 20px;
            font-size: 2.5em;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
        }
        .welcome-container p {
            margin-bottom: 20px;
            line-height: 1.6;
            font-size: 1.2em;
        }
        .welcome-container p a {
            color: #3498db;
            text-decoration: none;
            margin: 0 10px;
            padding: 10px 20px;
            border: 1px solid #3498db;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }
        .welcome-container p a:hover {
            color: #f1f5f9;
            background-color: #3498db;
        }
    </style>
    <div class="welcome-container">
        <h1>Welcome to InfiniLearn AI</h1>
        <p>
            InfiniLearn AI is your guide to curated, top-tier content from across the internet. With the power of AI, we create a personalized learning plan for you to master any skill you desire.
        </p>
        <p>
            Ready to start learning? 
            <a href="{{ url_for('main.login') }}">Login</a> or 
            <a href="{{ url_for('main.register') }}">Register</a>
        </p>
    </div>
{% endblock %}

my_platform/app/templates/learning_paths.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .content-heading {
            text-align: center;
            color: #3498db;
            margin-top: 20px;
        }
        .learning-paths {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 15px;
            margin: 20px 0;
            padding: 0;
            list-style-type: none;
        }
        .learning-path-item {
            display: flex;
            flex-direction: column;
            align-items: center;
            border: 1px solid #3498db;
            border-radius: 10px;
            padding: 20px;
            text-align: center;
            background-color: #f1f5f9;
            transition: transform 0.3s;
            max-width: 300px;
        }
        .learning-path-item:hover {
            transform: translateY(-5px);
            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.1);
        }
        .learning-path-item h3 {
            margin-bottom: 10px;
        }
        .learning-path-item p {
            margin: 5px 0;
        }
        .learning-path-item a {
            color: #3498db;
            text-decoration: none;
            font-weight: bold;
            margin-top: 10px;
        }
    </style>
    <h2 class="content-heading">My Learning Plans</h2>
    <ul class="learning-paths">
    {% for path in paths %}
        <li class="learning-path-item">
            <h3>{{ path.title }}</h3>
            <p>Topic: {{ path.topic_of_study }}</p>
            <p>Duration: {{ path.time_frame }} weeks</p>
            <a href="{{ url_for('main.view_learning_path', path_id=path.id) }}">View Learning Path</a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

my_platform/app/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .login-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: calc(100vh - 100px); /* assuming 100px as the height of your nav */
        }
        .login-box {
            border: 1px solid #3498db;
            border-radius: 10px;
            padding: 20px;
            width: 300px;
            background-color: #f1f5f9;
        }
        .login-box h2 {
            text-align: center;
            color: #3498db;
            margin-bottom: 20px;
        }
        .login-box form div {
            margin-bottom: 10px;
        }
        .login-box form div:last-child {
            text-align: center;
        }
    </style>
    <div class="login-container">
        <div class="login-box">
            <h2>Log In</h2>
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <div>
                    {{ form.email.label }}<br>
                    {{ form.email(size=32) }}
                </div>
                <div>
                    {{ form.password.label }}<br>
                    {{ form.password(size=32) }}
                </div>
                <div>
                    {{ form.remember_me() }} {{ form.remember_me.label }}
                </div>
                <div>
                    {{ form.submit() }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

my_platform/app/templates/personalized_learning_path.html
<!-- app/templates/personalized_learning_path.html -->
{% extends 'base.html' %}

{% block content %}
<h2>{{ learning_path.title }}</h2>
<ul>
{% for content in learning_path.contents %}
    <li>{{ content.title }}</li>
{% endfor %}
</ul>
{% endblock %}

my_platform/app/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<style>
    .card {
        background-color: #f1f5f9;
        border-radius: 10px;
        box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.2);
        padding: 20px;
        margin: 20px auto;
        max-width: 500px; /* adjust as needed */
    }
    .card h2 {
        text-align: center;
    }
    .card label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
    }
    .card-input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        transition: border-color 0.3s;
        box-sizing: border-box;
    }
    .card-input:focus {
        outline: none;
        border-color: #3498db;
    }
    .card button {
        display: block;
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 5px;
        background-color: #3498db;
        color: #fff;
        font-weight: bold;
        transition: background-color 0.3s;
        cursor: pointer;
    }
    .card button:hover {
        background-color: #1a5276;
    }
    .text-danger {
        color: red;
        font-size: 0.8em; /* adjust as needed */
    }
</style>

<div class="card">
    <h2>User Profile</h2>
    <form method="post">
        {{ form.csrf_token }}
        <div>
            <label for="{{ form.username.id }}">Username</label>
            {{ form.username(class="card-input") }}
            {% for error in form.username.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            <label for="{{ form.email.id }}">Email</label>
            {{ form.email(class="card-input") }}
            {% for error in form.email.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>

{% endblock %}

my_platform/app/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .register-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: calc(100vh - 100px); /* assuming 100px as the height of your nav */
        }
        .register-box {
            border: 1px solid #3498db;
            border-radius: 10px;
            padding: 20px;
            width: 300px;
            background-color: #f1f5f9;
        }
        .register-box h2 {
            text-align: center;
            color: #3498db;
            margin-bottom: 20px;
        }
        .register-box form div {
            margin-bottom: 10px;
        }
        .register-box form div:last-child {
            text-align: center;
        }
        .flash-message {
            color: red;
            text-align: center;
            margin-bottom: 10px;
        }
    </style>
    <div class="register-container">
        <div class="register-box">
            <h2>Register</h2>
            <!-- Flash messages -->
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="flash-message">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <div>
                    {{ form.username.label }}<br>
                    {{ form.username(size=32) }}
                    {% if form.username.errors %}
                        <ul class="errors">
                            {% for error in form.username.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div>
                    {{ form.email.label }}<br>
                    {{ form.email(size=32) }}
                    {% if form.email.errors %}
                        <ul class="errors">
                            {% for error in form.email.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div>
                    {{ form.password.label }}<br>
                    {{ form.password(size=32) }}
                    {% if form.password.errors %}
                        <ul class="errors">
                            {% for error in form.password.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div>
                    {{ form.password_confirm.label }}<br>
                    {{ form.password_confirm(size=32) }}
                    {% if form.password_confirm.errors %}
                        <ul class="errors">
                            {% for error in form.password_confirm.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div>
                    {{ form.submit() }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}